name: Cypress Tests

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2